from __future__ import annotations

from pathlib import Path
from typing import Sequence


RHINO_VARIANTS = ("kld", "riou")


def _python_tuple(values: Sequence[str]) -> str:
    escaped = [value.replace("\\", "\\\\").replace("'", "\\'") for value in values]
    suffix = "," if len(escaped) == 1 else ""
    return "(" + ", ".join(f"'{value}'" for value in escaped) + suffix + ")"


def render_rhino_config(
    base_config: Path,
    data_root: Path,
    class_names: Sequence[str],
    variant: str,
    imgsz: int,
    epochs: int,
    batch: int,
    workers: int,
) -> str:
    if variant not in RHINO_VARIANTS:
        raise ValueError(f"variant must be one of {RHINO_VARIANTS}, got {variant!r}")
    if imgsz <= 0 or epochs <= 0 or batch <= 0 or workers < 0:
        raise ValueError("imgsz, epochs, batch must be positive and workers must be non-negative")
    if not class_names:
        raise ValueError("at least one class is required")

    milestones = [max(1, round(epochs * 0.75)), max(1, round(epochs * 0.92))]
    classes = _python_tuple(list(class_names))
    data_root_text = str(data_root.resolve()).replace("\\", "\\\\").replace("'", "\\'") + "/"
    base_text = str(base_config.resolve()).replace("\\", "\\\\").replace("'", "\\'")
    persistent_workers = "True" if workers > 0 else "False"
    if variant == "kld":
        regression = "dict(type='GDLoss', loss_type='kld', fun='log1p', tau=1, sqrt=False, loss_weight=5.0)"
        costs = "[dict(type='mmdet.FocalLossCost', weight=2.0), dict(type='HausdorffCost', weight=5.0, box_format='xywha'), dict(type='GDCost', loss_type='kld', fun='log1p', tau=1, sqrt=False, weight=5.0)]"
    else:
        regression = "dict(_delete_=True, type='RotatedIoULoss', mode='linear', loss_weight=5.0)"
        costs = "[dict(type='mmdet.FocalLossCost', weight=2.0), dict(type='HausdorffCost', weight=5.0, box_format='xywha'), dict(type='RotatedIoUCost', iou_mode='iou', weight=5.0)]"

    return f'''# Generated by scripts/train_rhino.py. Do not edit this file manually.
_base_ = r'{base_text}'

classes = {classes}
metainfo = dict(classes=classes)
data_root = r'{data_root_text}'
max_epochs = {epochs}

train_pipeline = [
    dict(type='mmdet.LoadImageFromFile'),
    dict(type='mmdet.LoadAnnotations', with_bbox=True, box_type='qbox'),
    dict(type='ConvertBoxType', box_type_mapping=dict(gt_bboxes='rbox')),
    dict(type='mmdet.Resize', scale=({imgsz}, {imgsz}), keep_ratio=True),
    dict(type='mmdet.RandomFlip', prob=0.75, direction=['horizontal', 'vertical', 'diagonal']),
    dict(type='mmdet.PackDetInputs'),
]
test_pipeline = [
    dict(type='mmdet.LoadImageFromFile'),
    dict(type='mmdet.Resize', scale=({imgsz}, {imgsz}), keep_ratio=True),
    dict(type='mmdet.LoadAnnotations', with_bbox=True, box_type='qbox'),
    dict(type='ConvertBoxType', box_type_mapping=dict(gt_bboxes='rbox')),
    dict(type='mmdet.PackDetInputs', meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor')),
]

train_dataloader = dict(
    batch_size={batch}, num_workers={workers}, persistent_workers={persistent_workers},
    dataset=dict(data_root=data_root, ann_file='train/annfiles/', data_prefix=dict(img_path='train/images/'),
                 metainfo=metainfo, img_shape=({imgsz}, {imgsz}), filter_cfg=dict(filter_empty_gt=False), pipeline=train_pipeline),
)
val_dataloader = dict(
    batch_size=1, num_workers={workers}, persistent_workers={persistent_workers}, drop_last=False,
    dataset=dict(data_root=data_root, ann_file='test/annfiles/', data_prefix=dict(img_path='test/images/'),
                 metainfo=metainfo, img_shape=({imgsz}, {imgsz}), test_mode=True, pipeline=test_pipeline),
)
test_dataloader = val_dataloader
val_evaluator = dict(_delete_=True, type='DOTAMetric', metric='mAP', iou_thr=0.5)
test_evaluator = dict(_delete_=True, type='DOTAMetric', metric='mAP', iou_thr=0.5)

model = dict(
    bbox_head=dict(num_classes={len(class_names)}, loss_iou={regression}),
    train_cfg=dict(
        assigner=dict(match_costs={costs}),
        dn_assigner=dict(type='DNGroupHungarianAssigner', match_costs={costs}),
    ),
)
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=max_epochs, val_interval=1)
param_scheduler = [dict(type='MultiStepLR', begin=0, end=max_epochs, by_epoch=True, milestones={milestones}, gamma=0.1)]
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='AdamW', lr=0.0001, weight_decay=0.0001),
    clip_grad=dict(max_norm=0.1, norm_type=2),
    paramwise_cfg=dict(custom_keys={{'backbone': dict(lr_mult=0.1)}}),
)
default_hooks = dict(checkpoint=dict(type='CheckpointHook', interval=1, save_best='dota/mAP', rule='greater', max_keep_ckpts=2))
'''
